# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'google-protobuf'
gem 'googleapis-common-protos-types'
gem 'grpc'
gem 'grpc-tools'
gem 'observer'
gem 'ruby-protocol-buffers'
gem 'ruby_protobuf'
gem 'http'
gem 'bundler'