# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("student.proto", :syntax => :proto3) do
    add_message "StudentModule.Student" do
      optional :ra, :int32, 1
      optional :name, :string, 2
      optional :period, :int32, 3
      optional :course_code, :int32, 4
    end
    add_message "StudentModule.StudentsResponse" do
      repeated :students, :message, 1, "StudentModule.Student"
    end
    add_message "StudentModule.UpdateGradeRequest" do
      optional :subject_code, :string, 1
      optional :student_ra, :int32, 2
      optional :year, :int32, 3
      optional :semester, :int32, 4
      optional :grade, :float, 5
    end
    add_message "StudentModule.StudentQueryBySubjectRequest" do
      optional :subject_code, :string, 1
      proto3_optional :year, :int32, 2
      proto3_optional :semester, :int32, 3
    end
  end
end

module StudentModule
  Student = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StudentModule.Student").msgclass
  StudentsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StudentModule.StudentsResponse").msgclass
  UpdateGradeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StudentModule.UpdateGradeRequest").msgclass
  StudentQueryBySubjectRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StudentModule.StudentQueryBySubjectRequest").msgclass
end
