# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='student.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rstudent.proto\"H\n\x07Student\x12\n\n\x02ra\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06period\x18\x03 \x01(\x05\x12\x13\n\x0b\x63ourse_code\x18\x04 \x01(\x05\"\x1f\n\x11getStudentRequest\x12\n\n\x02ra\x18\x01 \x01(\x05\"/\n\x12getStudentResponse\x12\x19\n\x07student\x18\x01 \x01(\x0b\x32\x08.Student\"1\n\x13getStudentsResponse\x12\x1a\n\x08students\x18\x01 \x03(\x0b\x32\x08.Studentb\x06proto3'
)




_STUDENT = _descriptor.Descriptor(
  name='Student',
  full_name='Student',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='Student.ra', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Student.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='period', full_name='Student.period', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='course_code', full_name='Student.course_code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=89,
)


_GETSTUDENTREQUEST = _descriptor.Descriptor(
  name='getStudentRequest',
  full_name='getStudentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ra', full_name='getStudentRequest.ra', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=122,
)


_GETSTUDENTRESPONSE = _descriptor.Descriptor(
  name='getStudentResponse',
  full_name='getStudentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='student', full_name='getStudentResponse.student', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=171,
)


_GETSTUDENTSRESPONSE = _descriptor.Descriptor(
  name='getStudentsResponse',
  full_name='getStudentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='students', full_name='getStudentsResponse.students', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=222,
)

_GETSTUDENTRESPONSE.fields_by_name['student'].message_type = _STUDENT
_GETSTUDENTSRESPONSE.fields_by_name['students'].message_type = _STUDENT
DESCRIPTOR.message_types_by_name['Student'] = _STUDENT
DESCRIPTOR.message_types_by_name['getStudentRequest'] = _GETSTUDENTREQUEST
DESCRIPTOR.message_types_by_name['getStudentResponse'] = _GETSTUDENTRESPONSE
DESCRIPTOR.message_types_by_name['getStudentsResponse'] = _GETSTUDENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Student = _reflection.GeneratedProtocolMessageType('Student', (_message.Message,), {
  'DESCRIPTOR' : _STUDENT,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:Student)
  })
_sym_db.RegisterMessage(Student)

getStudentRequest = _reflection.GeneratedProtocolMessageType('getStudentRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSTUDENTREQUEST,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:getStudentRequest)
  })
_sym_db.RegisterMessage(getStudentRequest)

getStudentResponse = _reflection.GeneratedProtocolMessageType('getStudentResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTUDENTRESPONSE,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:getStudentResponse)
  })
_sym_db.RegisterMessage(getStudentResponse)

getStudentsResponse = _reflection.GeneratedProtocolMessageType('getStudentsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSTUDENTSRESPONSE,
  '__module__' : 'student_pb2'
  # @@protoc_insertion_point(class_scope:getStudentsResponse)
  })
_sym_db.RegisterMessage(getStudentsResponse)


# @@protoc_insertion_point(module_scope)
