#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class Enrollment < ::ProtocolBuffers::Message; end
class EnrollmentsResponse < ::ProtocolBuffers::Message; end
class EnrollmentPkRequest < ::ProtocolBuffers::Message; end
class EnrollmentQueryBySubjectRequest < ::ProtocolBuffers::Message; end
class UpdateEnrollmentRequest < ::ProtocolBuffers::Message; end

class Enrollment < ::ProtocolBuffers::Message
  set_fully_qualified_name "Enrollment"

  optional :string, :subject_code, 1
  optional :int32, :student_ra, 2
  optional :int32, :year, 3
  optional :int32, :semester, 4
  optional :float, :grade, 5
  optional :int32, :abscenses, 6
end

class EnrollmentsResponse < ::ProtocolBuffers::Message
  set_fully_qualified_name "EnrollmentsResponse"

  repeated ::Enrollment, :enrollments, 1
end

class EnrollmentPkRequest < ::ProtocolBuffers::Message
  set_fully_qualified_name "EnrollmentPkRequest"

  optional :string, :subject_code, 1
  optional :int32, :student_ra, 2
  optional :int32, :year, 3
  optional :int32, :semester, 4
end

class EnrollmentQueryBySubjectRequest < ::ProtocolBuffers::Message
  set_fully_qualified_name "EnrollmentQueryBySubjectRequest"

  optional :string, :subject_code, 1
  optional :int32, :year, 2
  optional :int32, :semester, 3
end

class UpdateEnrollmentRequest < ::ProtocolBuffers::Message
  set_fully_qualified_name "UpdateEnrollmentRequest"

  optional :string, :subject_code, 1
  optional :int32, :student_ra, 2
  optional :int32, :year, 3
  optional :int32, :semester, 4
  optional :float, :grade, 5
  optional :int32, :abscenses, 6
end

