#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class Response < ::ProtocolBuffers::Message; end

class Response < ::ProtocolBuffers::Message
  set_fully_qualified_name "Response"

  optional :int32, :status, 1
  optional :string, :message, 2
end

