#!/usr/bin/env ruby
# Generated by the protocol buffer compiler. DO NOT EDIT!

require 'protocol_buffers'

# forward declarations
class Student < ::ProtocolBuffers::Message; end
class StudentsResponse < ::ProtocolBuffers::Message; end
class UpdateGradeRequest < ::ProtocolBuffers::Message; end
class StudentQueryByEnrollmentRequest < ::ProtocolBuffers::Message; end

class Student < ::ProtocolBuffers::Message
  set_fully_qualified_name "Student"

  optional :int32, :ra, 1
  optional :string, :name, 2
  optional :int32, :period, 3
  optional :int32, :course_code, 4
end

class StudentsResponse < ::ProtocolBuffers::Message
  set_fully_qualified_name "StudentsResponse"

  repeated ::Student, :students, 1
end

class UpdateGradeRequest < ::ProtocolBuffers::Message
  set_fully_qualified_name "UpdateGradeRequest"

  optional :string, :subject_code, 1
  optional :int32, :student_ra, 2
  optional :int32, :year, 3
  optional :int32, :semester, 4
  optional :float, :grade, 5
end

class StudentQueryByEnrollmentRequest < ::ProtocolBuffers::Message
  set_fully_qualified_name "StudentQueryByEnrollmentRequest"

  optional :string, :subject_code, 1
  optional :int32, :year, 2
  optional :int32, :semester, 3
end

